#!/usr/bin/env bash
#
# fff - fucking fast file-manager.

refresh() {
    printf '\e[?7l\e[?25l\e[2J\e[H'
    shopt -s checkwinsize; (:;:)
    [[ -z "${LINES:-$COLUMNS}" ]] && read -r LINES COLUMNS < <(stty size)
    ((j=LINES-3,m=j))
}

get_dir() {
    d=(); f=()
    for p in "$PWD"/*; do
        [[ -d "$p" ]] && d+=("$p")
        [[ -f "$p" ]] && f+=("$p")
    done
    f=("${d[@]}" "${f[@]}"); c="${#f[@]}"
}

f_print() {
    for((i=${k:=0};i<(j=j>c?c:j);i++));{
        path="${f[$i]##*/}"
        [[ -d "${f[$i]}" ]]           && path="\\e[1m\\e[31m${path}/\\e[m"
        [[ "${f[$i]}" == "${f[l]}" ]] && path="\\e[7m${path}\\e[m"
        printf '\e[K%b\n' "$path"
    }

    printf '\e[2m\e[%s;H\e[K\n\e[K%b\e[m\e[H' \
           "$((LINES-2))" "${PWD/\/\//\/} (${l:-1}/$((c-1))) $j $k $l"
}

open() {
    if [[ -d "${1:-/}" ]]; then
        ((k=0,l=0))
        refresh
        PWD="${1:-/}"
        get_dir
        f_print
    elif [[ -f "$1" ]]; then
        case "${1##*.}" in
            7z|a|apk|ar|bz2|cab|cpio|dmg|egg|gz|iso|jar|lha|mar|pea|rar|\
            rpm|s7z|shar|tar|tbz2|tgz|tlz|war|whl|xpi|zip|zipx|deb|xz|pak|\
            crx|exe|msi|bin|aac|aiff|ape|au|flac|gsm|it|m3u|m4a|mid|mod|mp3|\
            mpa|pls|ra|s3m|sid|wav|wma|xm|eot|otf|ttf|woff|woff2|3dm|3ds|max|\
            bmp|dds|gif|jpg|jpeg|png|ico|psd|xcf|tga|thm|tif|tiff|yuv|ai|eps|ps|\
            svg|dwg|dxf|gpx|kml|kmz|ods|xls|xlsx|ics|vcf|ppt|odp|3g2|3gp|aaf|\
            asf|avchd|avi|drc|flv|m2v|m4p|m4v|mkv|mng|mov|mp2|mp4|mpe|mpeg|\
            mpg|mpv|mxf|nsv|ogg|ogv|ogm|qt|rm|rmvb|roq|srt|svi|vob|webm|wmv|\
            doc|docx|ebook|msg|odt|pages|pdf|rtf|wpd|wps)
               nohup xdg-open "$1" >/dev/null 2>&1 &
            ;;

            *) "${EDITOR:-vi}" "$1"; printf '\e[?25l' ;;
        esac
    fi
}

key() {
    case "${1: -1}" in
        B|j) ((l==c-1))||((l++));((j==c))||((k=k>=j?k:++k,j=j<c?++j:j)) ;;
        A|k) ((l==0))||((l--));((k==0))||((k=k<=j?k>0?--k:0:j,j=j>0?--j:j)) ;;
        C|l) open "${f[l]}" ;;
        D|h) open "${PWD%/*}" ;;
        g)   ((l=0,k=0)); refresh ;;
        G)   ((j==c))||((k=c-m,j=c,l=c-1)); f_print ;;
    esac
}

main() {
    refresh
    get_dir
    f_print

    trap $'printf \'\e[2J\e[?7h\e[?25h\'; cd $PWD; exec $SHELL' EXIT
    trap  'refresh; k=0; l=0; f_print' SIGWINCH

    for ((;;)); { f_print; read -rs -n 1; key "$REPLY"; }
}

main "$@"
