.TH FFF "1" "October 2018" "fff-dev" "User Commands"
.SH NAME
fff \- :rocket: fucking fast file-manager
.SH SYNOPSIS
.B fff
.SH DESCRIPTION
A [WIP] simple file manager written in bash. It's Fucking Fast, Minimal (~100 lines of bash), Smooth Scrolling (using vim keybindings.), File Operations (copy, paste, rename, cut, delete), Basic Search.
.PP
.SH KEYBINDINGS
.TP

\fBj\fR
scroll down
.TP
\fBk\fR
scroll up
.TP
\fBh\fR
go to parent dir
.TP
\fBl\fR
go to child dir
.TP

\fBenter\fR
go to child dir
.TP

\fBg\fR
go to top
.TP
\fBG\fR
go to bottom
.TP

\fB.\fR
toggle hidden files
.TP
\fB/\fR
search
.TP
\fBt\fR
go to trash
.TP
\fB~\fR
go to home
.TP
\fBs\fR
open shell in current dir
.TP
\fBx\fR
view file/dir attributes
.TP

.TP
\fB[1-9]\fR
favourites (see customization)

\fBdown\fR
scroll down
.TP
\fBup\fR
scroll up
.TP
\fBleft\fR
go to parent dir
.TP
\fBright\fR
go to child dir
.TP

\fBf\fR
new file
.TP
\fBn\fR
new dir
.TP
\fBy\fR
mark copy
.TP
\fBm\fR
mark move
.TP
\fBp\fR
paste/move
.TP
\fBc\fR
clear file selections
.TP
\fBr\fR
rename
.TP
\fBd\fR
trash (~/.cache/fff/trash/)

.TP
\fBq\fR
exit

.PP
.SH CUSTOMIZATION
.TP

\fBDirectory color [0-9]\fR
export FFF_COL1=2
.TP
\fBStatus color [0-9]\fR
export FFF_COL2=7
.TP
\fBSelection color [0-9] (copied/moved files)\fR
export FFF_COL3=1
.TP
\fBCursor color [0-9]\fR
export FFF_COL4=6
.TP
\fBText Editor\fR
export EDITOR="vim"
.TP
\fBFile Opener\fR
export FFF_OPENER="xdg-open"
.TP
\fBCD on exit helper file\fR
# (bash):        alias f='fff; cd "$(< ~/.fff_d)"'

# (posix):       alias f='fff; cd "$(cat ~/.fff_d)"'

# (alternative): function f() { fff "$@"; cd "$(< ~/.fff_d)"; }

export FFF_CD_FILE=~/.fff_d
.TP
\fBTrash Directory\fR
export FFF_TRASH=~/.cache/fff/trash
.TP

\fBFavourites (keys 1-9) (dir or file)\fR
export FFF_FAV1=~/projects

export FFF_FAV2=~/.bashrc

export FFF_FAV3=~/Pictures/Wallpapers/

export FFF_FAV4=/usr/share

export FFF_FAV5=/

export FFF_FAV6=

export FFF_FAV7=

export FFF_FAV8=

export FFF_FAV9=
.TP
