.
.TH FFF "1" "January 2019" "fff" "User Commands"
.SH NAME
fff \- :file_folder: A simple file manager written in bash
.SH SYNOPSIS
.B fff
.SH DESCRIPTION
A simple file manager written in bash.
.PP
.SH "Usage"
.
.nf

j: scroll down
k: scroll up
h: go to parent dir
l: go to child dir

enter: go to child dir/open file
backspace: go to parent dir
o: open file with
O: open file with GUI program detached from file manager

\-: Go to previous dir\.

g: go to top
G: go to bottom

:: go to a directory by typing.

\.: toggle hidden files
/: search
t: go to trash
~: go to home
z: refresh current dir
!: open shell in current dir

i: display file details
I: display an image using sixel
u: sort files
x: view file/dir attributes
e: show history

down:  scroll down
up:    scroll up
left:  go to parent dir
right: go to child dir

f: new file
n: new dir
r: rename
X: toggle executable
y: copy filename to clipboard

space: mark file
a: mark all files in directory
c: copy
m: move
d: trash (move to FFF_TRASH)
s: symbolic link
b: bulk rename

p: execute paste/move/delete/bulk_rename

[1-9]: favourites/bookmarks (see customization)

q: exit with 'cd' (if enabled).
Ctrl+C: exit without 'cd'.

?: show help
.
.fi
.
.SH "Customization"
.
.nf

# Use LS_COLORS to color fff.
# (On by default if available)
# (Ignores FFF_COL1)
export FFF_LS_COLORS=1

# Show/Hide hidden files on open.
# (On by default)
export FFF_HIDDEN=0

# Show/Hide file icons on open
# (Off by default)
export FFF_FILE_ICON=1

# Show/Hide git status signs (+) on open
# (Off by default)
export FFF_GIT_CHANGES=1

# Default method to sort files on open
# 0 - alphabetically
# 1 - modification time
# (0 by default)
export FFF_SORT_METHOD=1

# Show/Hide file details on open
# (Off by default)
export FFF_FILE_DETAILS=1

# Directory color [0\-9]
export FFF_COL1=2

# Status background color [0\-9]
export FFF_COL2=7

# Selection color [0\-9] (copied/moved files)
export FFF_COL3=6

# Cursor color [0\-9]
export FFF_COL4=1

# Status foreground color [0\-9]
export FFF_COL5=0

# Selection color
# (inverted foreground by default)
# ('48;2;R;G;B' values separated by ';', don't edit the '48;2;' part!).
# In terminals that support truecolor, this will set the selection color
# to grey, but on others selection will be only white bold text (if this
# is set).
export FFF_COL6="48;2;80;80;80"

# Colored filenames
# (0 by default)
export FFF_COLORED_FILENAMES=1

# Text Editor
export EDITOR="nvim"

# Text Editor
export EDITOR="vim"

# File Opener
export FFF_OPENER="xdg\-open"

# File Attributes Command
export FFF_STAT_CMD="stat"

# Enable or disable CD on exit.
# Default: '1'
export FFF_CD_ON_EXIT=1

# CD on exit helper file
# Default: '${XDG_CACHE_HOME}/fff/fff.d'
#          If not using XDG, '${HOME}/.cache/fff/fff.d' is used.
export FFF_CD_FILE=~/.fff_d

# Trash Directory
# Default: '${XDG_DATA_HOME}/fff/trash'
#          If not using XDG, '${XDG_DATA_HOME}/fff/trash' is used.
export FFF_TRASH=~/.local/share/fff/trash

# Trash Command
# Default: 'mv'
#          Define a custom program to use to trash files.
#          The program will be passed the list of selected files
#          and directories.
export FFF_TRASH_CMD="mv"

# Favourites (Bookmarks) (keys 1-9) (dir or file)
export FFF_FAV1=~/projects
export FFF_FAV2=~/.bashrc
export FFF_FAV3=~/Pictures/Wallpapers/
export FFF_FAV4=/usr/share
export FFF_FAV5=/
export FFF_FAV6=
export FFF_FAV7=
export FFF_FAV8=
export FFF_FAV9=

# History file length.
# (100 lines by default)
# Every cd-on-exit (q) program deletes every line older than
# FFF_HISTORY_LENGTH.
# Example: history has 150 lines, quitting trims history file
# to 100 most recent.
export FFF_HISTORY_LENGTH=200

# File format.
# Customize the item string.
# Format ('%f' is the current file): "str%fstr"
# Example (Add a tab before files): FFF_FILE_FORMAT="\t%f"
export FFF_FILE_FORMAT="%f"

# Mark format.
# Customize the marked item string.
# Format ('%f' is the current file): "str%fstr"
# Example (Add a ' >' before files): FFF_MARK_FORMAT="> %f"
export FFF_MARK_FORMAT=" %f*"

# Clipboard program and arguments.
# Default: xclip -selection c 
export FFF_KEY_CLIPBOARD="xclip -selection c"

# Scroll steps.
# (14 by default).
export FFF_SCROLL_UP=14
export FFF_SCROLL_DOWN=14

# Sixel image program.
# Default: img2sixel
export FFF_SIXEL_CMD="img2sixel"
.
.fi
.
.SH "Keybindings"
.
.nf
For more information see:
    https://github.com/piotr-marendowski/fff#customizing-the-keybindings

### Moving around.

# Go to child directory.
export FFF_KEY_CHILD1="l"
export FFF_KEY_CHILD2=$'\e[C' # Right Arrow
export FFF_KEY_CHILD3=""      # Enter / Return

# Go to parent directory.
export FFF_KEY_PARENT1="h"
export FFF_KEY_PARENT2=$'\e[D' # Left Arrow
export FFF_KEY_PARENT3=$'\177' # Backspace
export FFF_KEY_PARENT4=$'\\b'   # Backspace (Older terminals)

# Go to previous directory.
export FFF_KEY_PREVIOUS="-"

# Search.
export FFF_KEY_SEARCH="/"

# Spawn a shell.
export FFF_KEY_SHELL="!"

# Scroll down.
export FFF_KEY_SCROLL_DOWN1="j"
export FFF_KEY_SCROLL_DOWN2=$'\e[B' # Down Arrow

# Scroll up.
export FFF_KEY_SCROLL_UP1="k"
export FFF_KEY_SCROLL_UP2=$'\e[A'   # Up Arrow

# Go to top and bottom.
export FFF_KEY_TO_TOP="g"
export FFF_KEY_TO_BOTTOM="G"

# Go to dirs.
export FFF_KEY_GO_DIR=":"
export FFF_KEY_GO_HOME="~"
export FFF_KEY_GO_TRASH="t"

### File operations.
export FFF_KEY_MARK=" "
export FFF_KEY_MARK_ALL="v"
export FFF_KEY_COPY="c"
export FFF_KEY_MOVE="m"
export FFF_KEY_TRASH="d"
export FFF_KEY_LINK="s"
export FFF_KEY_BULK_RENAME="b"

export FFF_KEY_EXECUTE="p"

export FFF_KEY_RENAME="r"
export FFF_KEY_MKDIR="n"
export FFF_KEY_MKFILE="f"

### Miscellaneous

# Display file details.
export FFF_KEY_DETAILS="i"

# Display an image using sixel.
export FFF_KEY_SIXEL="I"

# Sort files.
export FFF_KEY_SORT="u"

# Show file attributes.
export FFF_KEY_ATTRIBUTES="x"

# Toggle executable flag.
export FFF_KEY_EXECUTABLE="X"

# Toggle hidden files.
export FFF_KEY_HIDDEN="."

# Show history of directories. 
export FFF_KEY_HISTORY="e"

# Yank filename to clipboard.
export FFF_KEY_CLIPBOARD="y"
.
.fi

.SH "Disabling keybindings"
.
.nf

You can't unset keybindings by making their value `''`.
What you need to do is change their value to `off`.

Example:

# KEY_GO_TRASH was bound to 't', now its unset.
export FFF_KEY_GO_TRASH="off"

# KEY_MKFILE is now set to 't' and its original
# keybinding is also unset 'f'.
export FFF_KEY_MKFILE="t"
.
.fi

.SH "Dealing with conflicting keybindings"
.
.nf

When rebinding a key in `fff` make sure you don't have two bindings
with the same value. You can avoid this by setting the other
conflicting key-binding to something else or by changing its value to `off`.

.
.fi
